parameters:
  buildConfiguration: 'Release'
  environmentName: 'dev'
  webAppName: 'WebAppNameDev'

jobs:
- deployment: Deploy_${{ parameters.environmentName }}
  pool:
    vmImage: 'ubuntu-22.04'

  environment: ${{ parameters.environmentName }}
  variables:
  - group: 'Release'

  strategy:
    runOnce:
      deploy:

        steps:
        - download: current
          artifact: drop 

        - task: AzureWebApp@1
          condition: ne(variables['Environment.Name'], 'staging')
          displayName: 'Azure App Service Deploy Test'
          inputs:
            azureSubscription: 'Azure service connection - Name'
            appName: '$(${{ parameters.appName }})'
            package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'
        
        - task: AzureWebApp@1
          condition: eq(variables['Environment.Name'], 'staging')
          displayName: 'Azure App Service Deploy Pre-production'
          inputs:
            azureSubscription: 'Azure service connection - Name'
            deployToSlotOrASE: 'true'
            resourceGroupName: 'Resource Group - Name'
            slotName: 'swap'
            appName: '$(${{ parameters.appName }})'
            package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'