parameters:
  buildConfiguration: 'Release'
  environmentName: 'dev'
  functionAppName: 'AppName'

jobs:
- deployment: Deploy_${{ parameters.environmentName }}
  pool:
    vmImage: 'ubuntu-22.04'

  environment: ${{ parameters.environmentName }}
  variables:
  - group: 'Release'

  strategy:
    runOnce:
      deploy:

        steps:
        - download: current
          artifact: drop

        - task: AzureFunctionApp@2
          displayName: 'Azure Function Deploy Functions'
          inputs:
            connectedServiceNameARM: 'Azure service connection - Name'
            appName: '$(${{ parameters.functionAppName }})'
            package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'