parameters:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.x'

jobs:
  - job: 'RunUnitTests'
    dependsOn: Deploy
    displayName: 'Run unit tests'
    pool:
      vmImage: 'windows-2019'
    variables:
    - group: 'Release'

    steps: 
    - task: UseDotNet@2
      displayName: 'Use .NET SDK ${{ parameters.dotnetSdkVersion }}'
      inputs:
        version: '${{ parameters.dotnetSdkVersion }}'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
      inputs:
        command: 'build'
        arguments: '--configuration ${{ parameters.buildConfiguration }}'
        projects: '$(System.DefaultWorkingDirectory)/**/*test.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests - ${{ parameters.buildConfiguration }}'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '$(System.DefaultWorkingDirectory)/**/*test.csproj'