# App environment secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
data:
  DB_CONNECTION: SG9zdD1kYjtEYXRhYmFzZT1hcHBkYjtVc2VybmFtZT1hcHB1c2VyO1Bhc3N3b3JkPWNNNSo2QEZtaGZJeVY5fgo=
  #DB_CONNECTION: Host=db;Database=appdb;Username=appuser;Password=cM5*6@FmhfIyV9~
